
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - zstudio

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - COMPILER_PATH=/app/Compiler(Z--)/src/index.js
    volumes:
      - ./tmp:/tmp  # Uncomment if you need to persist temporary files
    networks:
      - zstudio

networks:
  zstudio:
    driver: bridge