name: Keep Render Backend Working

on:
  schedule:
    - cron: '30 4 * * *'   # once per day
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP ping to Render backend
        run: |
          curl -s https://z-studio.onrender.com/health-123
